steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/elitechwiz-ai', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/elitechwiz-ai']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'elitechwiz-ai'
      - '--image=gcr.io/$PROJECT_ID/elitechwiz-ai'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=1'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production,AI_PROVIDER=openai,AI_MODEL=gpt-4o,USE_PAIRING_CODE=true,LOG_LEVEL=info,PORT=8080,SESSION_DIR=./baileys_auth_info,ENABLE_WEBHOOK=false'
      - '--set-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest,ANTHROPIC_API_KEY=ANTHROPIC_API_KEY:latest,PHONE_NUMBER=PHONE_NUMBER:latest,WEBHOOK_URL=WEBHOOK_URL:latest,WEBHOOK_SECRET=WEBHOOK_SECRET:latest'
images:
  - 'gcr.io/$PROJECT_ID/elitechwiz-ai'
